const PDFS={1:'#',2:'#',3:'#',4:'#'};
const lessons=window.VIDA_LESSONS; const weekMeta=window.VIDA_WEEK_META; const materialTitles=window.VIDA_MATERIAL_TITLES;
const SUPABASE_URL='https://hvzlegeufiigjyanfyuu.supabase.co';
const SUPABASE_KEY='sb_publishable_hFLv8Q_9RCtHviptHWtEZw_FB7TXRqh';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let currentUser=null;
let state=JSON.parse(localStorage.getItem('vidaState')||'null')||{logged:false,profile:{name:'Participante',email:''},start:new Date().toISOString().slice(0,10),checks:{},water:0,sleep:'',weight:0,completed:[],planner:false,waitlist:false,role:'member',masterDay:null};
function save(){localStorage.setItem('vidaState',JSON.stringify(state))}
async function login(){const email=document.querySelector('#loginEmail').value.trim(),password=document.querySelector('#loginPass').value;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){toast(error.message);return}currentUser=data.user;await hydrateFromSupabase();showApp()}
async function signupTest(){const email=document.querySelector('#loginEmail').value.trim(),password=document.querySelector('#loginPass').value;if(!email||password.length<6){toast('Use e-mail válido e senha com 6+ caracteres');return}const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:email.split('@')[0]},emailRedirectTo:location.origin}});if(error){toast(error.message);return}if(data.session){currentUser=data.user;await bootstrapUser();await hydrateFromSupabase();showApp()}else toast('Conta criada. Confira o e-mail para confirmar o acesso.')}
function showApp(){state.logged=true;save();document.querySelector('#login').classList.add('hidden');document.querySelector('#root').classList.remove('hidden');go('home')}
async function bootstrapUser(){if(!currentUser)return;const name=currentUser.user_metadata?.full_name||currentUser.email?.split('@')[0]||'Participante';await sb.from('profiles').upsert({id:currentUser.id,email:currentUser.email,full_name:name});const {data:e}=await sb.from('enrollments').select('id,start_date').eq('user_id',currentUser.id).eq('program_slug','projeto-28').maybeSingle();if(!e)await sb.from('enrollments').insert({user_id:currentUser.id,program_slug:'projeto-28',start_date:new Date().toISOString().slice(0,10)})}
async function hydrateFromSupabase(){if(!currentUser)return;await bootstrapUser();const today=new Date().toISOString().slice(0,10);const [{data:p},{data:e},{data:c},{data:m},{data:f},{data:w},{data:cp}]=await Promise.all([sb.from('profiles').select('*').eq('id',currentUser.id).maybeSingle(),sb.from('enrollments').select('*').eq('user_id',currentUser.id).eq('program_slug','projeto-28').maybeSingle(),sb.from('daily_checkins').select('*').eq('user_id',currentUser.id).eq('checkin_date',today).maybeSingle(),sb.from('body_measurements').select('*').eq('user_id',currentUser.id).order('measured_on',{ascending:false}).limit(1).maybeSingle(),sb.from('feature_access').select('*').eq('user_id',currentUser.id).maybeSingle(),sb.from('club_waitlist').select('id').eq('user_id',currentUser.id).maybeSingle(),sb.from('content_progress').select('content_slug').eq('user_id',currentUser.id).eq('status','completed')]);state.profile={name:p?.full_name||currentUser.email?.split('@')[0]||'Participante',email:currentUser.email||''};state.role=currentUser.app_metadata?.vida_role||'member';state.start=e?.start_date||today;state.water=c?.water_ml||0;state.sleep=c?.sleep_minutes?`${Math.floor(c.sleep_minutes/60)}h${String(c.sleep_minutes%60).padStart(2,'0')}`:'';state.checks={water:(c?.water_ml||0)>0,movement:!!c?.trained||(c?.movement_minutes||0)>0,sleep:(c?.sleep_minutes||0)>0,daily:!!c?.daily_checkin_completed,content:(cp||[]).length>0};state.weight=m?.weight_kg?Number(m.weight_kg):0;state.completed=(cp||[]).map(x=>x.content_slug.replace('lesson-',''));state.planner=!!f?.planner_access;state.waitlist=!!w;save()}
async function syncCheckin(patch){if(!currentUser)return;const date=new Date().toISOString().slice(0,10);await sb.from('daily_checkins').upsert({user_id:currentUser.id,checkin_date:date,...patch},{onConflict:'user_id,checkin_date'})}
function navActive(s){document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===s))}
function go(s){navActive(s);const v=document.querySelector('#view'); if(s==='home')v.innerHTML=home(); if(s==='learn')v.innerHTML=learn(); if(s==='track')v.innerHTML=track(); if(s==='progress')v.innerHTML=progress(); if(s==='gym')v.innerHTML=gym(); if(s==='profile')v.innerHTML=profile(); window.scrollTo(0,0)}
function score(){const c=state.checks;return ['water','movement','sleep','daily','content'].filter(k=>c[k]).length*20}
function isMaster(){return state.role==='master'}
function day(){if(isMaster()&&state.masterDay)return Math.max(1,Math.min(28,Number(state.masterDay)));const a=new Date((state.start||new Date().toISOString().slice(0,10))+'T00:00:00');const b=new Date();return Math.max(1,Math.min(28,Math.floor((b-a)/86400000)+1))}
function setMasterDay(v){state.masterDay=Number(v);save();go('home')}
function masterPanel(){return isMaster()?`<div class="card" style="margin-top:12px;border-color:#171717"><div class="between row"><div><span class="badge">MASTER</span><h3 style="margin-top:8px">Modo de homologação</h3><p>Você pode simular qualquer dia para revisar todos os desbloqueios.</p></div><select onchange="setMasterDay(this.value)" style="width:88px;border:1px solid #ddd;border-radius:12px;padding:10px">${[1,8,15,22,28].map(x=>`<option value="${x}" ${day()===x?'selected':''}>Dia ${x}</option>`).join('')}</select></div></div>`:''}
function home(){const d=day();return `<section class="screen"><div class="hero"><div class="eyebrow">PROJETO 28 · DIA ${d} DE 28</div><h1>Sua jornada começa no que você consegue repetir.</h1><p>Conteúdo de emagrecimento, acompanhamento diário e constância em um único lugar.</p><button class="btn light" onclick="go('track')">CONTINUAR MEU DIA</button></div>${masterPanel()}<div class="grid2" style="margin-top:12px"><div class="card"><small>Score de Constância</small><div class="metric">${score()}%</div><div class="progress"><span style="width:${score()}%"></span></div></div><div class="card"><small>Seu momento</small><h3>Dia ${d}/28</h3><p>${weekMeta[currentWeek()].title}</p></div></div><div class="sectiontitle"><h2>Check-in de hoje</h2><small>5 ações</small></div><div class="checks">${checkRow('💧','Hidratação','water')}${checkRow('🏋️','Treino / movimento','movement')}${checkRow('😴','Sono','sleep')}${checkRow('✓','Check-in','daily')}${checkRow('📚','Conteúdo','content')}</div><div class="sectiontitle"><h2>Sua jornada</h2><small>conteúdo progressivo</small></div>${weeksList()}<div class="sectiontitle"><h2>Recursos</h2></div><div class="card" style="margin-bottom:10px"><div class="between row"><div><span class="badge">ADICIONAL</span><h3 style="margin-top:8px">Planner+</h3><p>Metas, planejamento semanal e histórico detalhado.</p></div><button class="btn" onclick="upgrade()">${state.planner?'ABRIR':'DESBLOQUEAR'}</button></div></div><div class="card"><span class="badge">ACESSO RESTRITO</span><h3 style="margin-top:8px">Carol Club</h3><p>Vagas encerradas no momento. Entre na lista para a próxima abertura.</p><button class="btn soft" style="margin-top:12px" onclick="clubWaitlist()">${state.waitlist?'VOCÊ ESTÁ NA LISTA':'ENTRAR NA LISTA'}</button></div></section>`}
function checkRow(icon,label,key){const on=!!state.checks[key];return `<div class="check ${on?'done':''}"><span>${icon}</span><div><b>${label}</b><div style="font-size:11px;color:#777">${on?'Registrado':'Ainda não registrado'}</div></div><button class="mark" onclick="toggleCheck('${key}')">${on?'✓':'+'}</button></div>`}
function toggleCheck(k){state.checks[k]=!state.checks[k];save();go('home')}
function currentWeek(){const d=day();return d>=22?4:d>=15?3:d>=8?2:1}
function weeksList(){const d=day();return [1,2,3,4].map(i=>{const m=weekMeta[i],open=isMaster()||d>=m.unlock;return `<div class="week ${open?'':'locked'}" ${open?`onclick="openWeek(${i})"`:''}><div class="weeknum">${i}</div><div class="weekbody"><b>Semana ${i} — ${m.title}</b><span>${lessons[i].length} ensinamentos + PDF + ${materialTitles[i].length} materiais</span></div><span class="tag ${open?'ok':''}">${open?'ABERTA':'DIA '+m.unlock}</span></div>`}).join('')}
function learn(){return `<section class="screen"><div class="hero"><div class="eyebrow">APRENDER</div><h1>Conhecimento em etapas.</h1><p>As ferramentas ficam disponíveis desde o começo. O aprofundamento abre aos poucos.</p></div><div class="sectiontitle"><h2>Projeto 28</h2><small>4 semanas</small></div>${weeksList()}</section>`}
function openWeek(i){const m=weekMeta[i];openModal(`<div class="moduleHero" style="background:${m.color}"><small>SEMANA ${i}</small><h1>${m.title}</h1><p>${lessons[i].length} ensinamentos, 1 guia principal e ${materialTitles[i].length} materiais adicionais.</p></div><div class="card"><h3>Ensinamentos</h3>${lessons[i].map((x,j)=>`<div class="lesson" onclick="openLesson(${i},${j})"><div class="lessonidx">${j+1}</div><div class="lessontext"><b>${x[0]}</b><span>${state.completed.includes(i+'-'+j)?'Concluído':'Abrir leitura'}</span></div><span>›</span></div>`).join('')}</div><div class="sectiontitle"><h2>Guia principal</h2></div><button class="btn full" onclick="toast('PDF aprovado — arquivo final entra nesta etapa')">GUIA PRINCIPAL APROVADO</button><div class="sectiontitle"><h2>Materiais adicionais</h2></div>${materialTitles[i].map((t,j)=>`<div class="material" onclick="openMaterial(${i},${j})"><b>${t}</b><span>Abrir ferramenta</span></div>`).join('')}`)}
function openLesson(i,j){const [t,b]=lessons[i][j];openModal(`<div class="article"><span class="badge">SEMANA ${i} · AULA ${j+1}</span><h2 style="margin-top:12px">${t}</h2>${md(b)}<button class="btn full" onclick="completeLesson(${i},${j})">${state.completed.includes(i+'-'+j)?'CONCLUÍDO ✓':'MARCAR COMO CONCLUÍDO'}</button></div>`)}
function md(s){return s.split('\n\n').map(p=>p.startsWith('> ')?`<div class="quote">${p.slice(2)}</div>`:`<p>${p.replace(/\n/g,'<br>')}</p>`).join('')}
async function completeLesson(i,j){const k=i+'-'+j;if(!state.completed.includes(k))state.completed.push(k);state.checks.content=true;save();if(currentUser)await sb.from('content_progress').upsert({user_id:currentUser.id,content_slug:'lesson-'+k,status:'completed',completed_at:new Date().toISOString()},{onConflict:'user_id,content_slug'});toast('Conteúdo concluído');openWeek(i)}
function openMaterial(i,j){const title=materialTitles[i][j];let body='';
 if(i===1&&j===0)body=`<div class="field"><label>Peso</label><input placeholder="kg"></div><div class="field"><label>Altura</label><input placeholder="cm"></div><div class="field"><label>Cintura</label><input placeholder="cm"></div><div class="field"><label>Principal objetivo</label><textarea></textarea></div><button class="btn full" onclick="toast('Diagnóstico salvo na V1 de teste')">SALVAR</button>`;
 else if(i===2&&j===6)body=`<p>Este simulador ensina a relação entre macros e energia. Não define quanto você deve consumir.</p><div class="field"><label>Proteína (g)</label><input id="p" type="number" value="35"></div><div class="field"><label>Carboidrato (g)</label><input id="c" type="number" value="55"></div><div class="field"><label>Gordura (g)</label><input id="f" type="number" value="15"></div><button class="btn full" onclick="macroCalc()">CALCULAR</button><div id="macroResult" class="notice" style="margin-top:10px"></div>`;
 else if(i===3&&j===8)body=`<p>Quer visualizar a execução de um exercício? Use uma biblioteca especializada para consultar nomes e demonstrações.</p><a class="btn full" style="display:block;text-align:center;text-decoration:none" href="https://musclewiki.com" target="_blank">ABRIR BIBLIOTECA DE EXERCÍCIOS</a><p class="notice" style="margin-top:10px">A demonstração não determina se o exercício é adequado para você.</p>`;
 else body=`<p>Material interativo da Semana ${i}. Na versão conectada ao Supabase, suas respostas ficam salvas no seu histórico.</p><div class="field"><label>Minha anotação</label><textarea rows="5" placeholder="Escreva aqui..."></textarea></div><button class="btn full" onclick="toast('Registro salvo na V1 de teste')">SALVAR REGISTRO</button>`;
 openModal(`<div class="article"><span class="badge">MATERIAL ADICIONAL</span><h2 style="margin-top:12px">${title}</h2>${body}</div>`)}
function macroCalc(){const p=+document.querySelector('#p').value,c=+document.querySelector('#c').value,f=+document.querySelector('#f').value;document.querySelector('#macroResult').innerHTML=`Proteína: ${p*4} kcal · Carboidrato: ${c*4} kcal · Gordura: ${f*9} kcal<br><b>Total estimado: ${p*4+c*4+f*9} kcal</b>`}
function track(){return `<section class="screen"><div class="hero"><div class="eyebrow">ACOMPANHAR</div><h1>Hoje conta.</h1><p>Registros simples para enxergar sua constância.</p></div><div class="grid2" style="margin-top:12px"><div class="card"><small>Hidratação</small><div class="metric">${state.water}</div><p>ml hoje</p><div class="row" style="margin-top:10px"><button class="btn soft" onclick="water(250)">+250</button><button class="btn soft" onclick="water(500)">+500</button></div></div><div class="card"><small>Sono</small><div class="metric" style="font-size:27px">${state.sleep||'--'}</div><p>último registro</p><button class="btn soft" style="margin-top:10px" onclick="sleepReg()">REGISTRAR</button></div></div><div class="sectiontitle"><h2>Rotina</h2></div><div class="card"><div class="check" style="border:0;padding:4px"><span>🏋️</span><div><b>Treino / movimento</b><div style="font-size:11px;color:#777">Registro do dia</div></div><button class="mark" onclick="state.checks.movement=true;save();toast('Movimento registrado');go('track')">${state.checks.movement?'✓':'+'}</button></div></div><div class="sectiontitle"><h2>Peso e medidas</h2></div><div class="card"><div class="between row"><div><small>Último peso</small><div class="metric" style="font-size:27px">${state.weight} kg</div></div><button class="btn soft" onclick="weightReg()">ATUALIZAR</button></div></div><div class="sectiontitle"><h2>Planner+</h2></div>${state.planner?`<div class="card"><h3>Minha semana</h3><p>Metas, plano B e revisão semanal já liberados.</p><button class="btn" style="margin-top:12px" onclick="openMaterial(3,0)">ABRIR PLANNER</button></div>`:`<div class="lockbox"><h3>🔒 Planner+</h3><p>Planejamento semanal, metas e histórico detalhado.</p><button class="btn" onclick="upgrade()">DESBLOQUEAR POR + R$ 6/MÊS</button></div>`}</section>`}
async function water(n){state.water+=n;state.checks.water=true;save();await syncCheckin({water_ml:state.water});go('track')}
function sleepReg(){openModal(`<h2>Registrar sono</h2><div class="field"><label>Horas dormidas</label><input id="sleepInput" placeholder="ex.: 7h10"></div><button class="btn full" onclick="saveSleep()">SALVAR</button>`)}
async function saveSleep(){const v=document.querySelector('#sleepInput').value.trim();const m=v.match(/(\d+)h?(\d+)?/i);const mins=m?(+m[1]*60+(m[2]?+m[2]:0)):0;state.sleep=v;state.checks.sleep=mins>0;save();await syncCheckin({sleep_minutes:mins});closeModal();go('track')}
function weightReg(){openModal(`<h2>Atualizar peso</h2><div class="field"><label>Peso (kg)</label><input id="wInput" type="number" step="0.1" value="${state.weight||''}"></div><button class="btn full" onclick="saveWeight()">SALVAR</button>`)}
async function saveWeight(){const v=+document.querySelector('#wInput').value;if(!v)return;state.weight=v;save();if(currentUser)await sb.from('body_measurements').insert({user_id:currentUser.id,weight_kg:v,measured_on:new Date().toISOString().slice(0,10)});closeModal();go('track')}
function progress(){const d=day(),done=state.completed.length,total=Object.values(lessons).flat().length;return `<section class="screen"><div class="hero"><div class="eyebrow">PROGRESSO</div><h1>Olhe para tendência, não para um único dia.</h1><p>Seu acompanhamento existe para mostrar o processo.</p></div><div class="grid2" style="margin-top:12px"><div class="stat"><b>${d}/28</b><span>Dias da jornada</span></div><div class="stat"><b>${score()}%</b><span>Constância hoje</span></div><div class="stat"><b>${done}</b><span>Conteúdos concluídos</span></div><div class="stat"><b>${state.weight} kg</b><span>Último peso</span></div></div><div class="card" style="margin-top:12px"><h3>Constância — últimos 7 dias</h3><div class="chart">${[55,80,65,90,72,85,score()||40].map(x=>`<div class="bar" style="height:${x}%"></div>`).join('')}</div></div><div class="card" style="margin-top:12px"><h3>Conteúdo</h3><p>${done} de ${total} ensinamentos concluídos.</p><div class="progress"><span style="width:${Math.round(done/total*100)}%"></span></div></div><p class="notice" style="margin-top:12px">Peso, IMC e medidas são indicadores limitados quando vistos isoladamente. O VIDA não usa esses números como diagnóstico de saúde.</p></section>`}
function gym(){return `<section class="screen"><div class="moduleHero" style="background:#161616"><small>PRÓXIMA FASE</small><h1>GYM RATS</h1><p>45 dias para continuar aparecendo e transformar constância em jogo.</p></div><div class="card"><h3>01/11 → 15/12</h3><p>O Projeto 28 ensina a base. O Gym Rats usa essa base como próxima etapa de constância.</p></div><div class="sectiontitle"><h2>Em preparação</h2></div><div class="card"><p>Regras, missões, pontuação e premiações serão publicados quando a mecânica final estiver fechada.</p></div></section>`}
function profile(){return `<section class="screen"><div class="hero"><div class="eyebrow">PERFIL</div><h1>${state.profile.name}</h1><p>${state.profile.email}</p>${isMaster()?'<span class="badge" style="background:#fff;color:#171717;margin-top:10px">ACESSO MASTER</span>':''}</div><div class="card" style="margin-top:12px"><h3>Meu acesso</h3><p>Projeto 28: ativo<br>Planner+: ${state.planner?'ativo':'não contratado'}<br>Carol Club: ${state.waitlist?'lista de espera':'vagas encerradas'}</p></div><div class="card" style="margin-top:12px"><h3>Sobre este conteúdo</h3><p>O VIDA / Projeto 28 é educacional e não substitui diagnóstico, consulta, prescrição nutricional, prescrição de exercício ou tratamento individual.</p></div><button class="btn outline full" style="margin-top:12px" onclick="logout()">SAIR</button></section>`}
function upgrade(){if(state.planner){go('track');return}openModal(`<h2>Planner+</h2><p>Você já acompanha. Agora pode planejar.</p><div class="card"><small>ADICIONAL</small><div class="metric" style="font-size:28px">+ R$ 6/mês</div><p>Metas, histórico detalhado e revisão semanal na mesma conta.</p></div><button class="btn full" style="margin-top:12px" onclick="state.planner=true;save();closeModal();toast('Planner+ liberado na simulação');go('track')">SIMULAR PAGAMENTO APROVADO</button><p class="notice" style="margin-top:10px">Na produção, este botão abrirá a Cakto. O webhook atualizará o Supabase e liberará o recurso automaticamente.</p>`)}
function clubWaitlist(){if(state.waitlist){toast('Você já está na lista');return}openModal(`<h2>Carol Club</h2><p>Vagas encerradas no momento.</p><div class="field"><label>Nome</label><input id="clubName" value="${state.profile.name}"></div><div class="field"><label>E-mail</label><input id="clubEmail" value="${state.profile.email}"></div><button class="btn full" onclick="joinClubWaitlist()">ENTRAR NA LISTA</button>`)}
async function joinClubWaitlist(){const email=document.querySelector('#clubEmail').value.trim();if(currentUser){const {error}=await sb.from('club_waitlist').upsert({user_id:currentUser.id,email,source:'app'},{onConflict:'email'});if(error){toast(error.message);return}}state.waitlist=true;save();closeModal();toast('Você entrou na lista de espera');go('home')}
function openModal(html){document.querySelector('#modalContent').innerHTML=html;document.querySelector('#modal').classList.add('open')}
function closeModal(){document.querySelector('#modal').classList.remove('open')}
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
async function logout(){await sb.auth.signOut();currentUser=null;state.logged=false;save();document.querySelector('#root').classList.add('hidden');document.querySelector('#login').classList.remove('hidden')}
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
(async()=>{const {data:{session}}=await sb.auth.getSession();if(session?.user){currentUser=session.user;await hydrateFromSupabase();showApp()}else{state.logged=false;save()}})();
