window.VIDA_GUIDES={
1:{title:'Entenda seu emagrecimento',subtitle:'Fundamentos para parar de tentar emagrecer no escuro.',sections:[['Antes de começar','Se você já tentou emagrecer, provavelmente recebeu regras diferentes e até contraditórias. Nesta semana, a proposta é entender os fundamentos antes de acelerar o resultado.'],['Emagrecer não é apenas perder peso','A balança mede peso total: água, músculos, ossos, órgãos, alimentos em digestão e gordura. Uma mudança rápida na balança não representa necessariamente a mesma mudança em gordura corporal.'],['Por que o peso muda','Água, sal, carboidratos armazenados, horário da pesagem, conteúdo intestinal, ciclo menstrual e recuperação do treino podem mudar o peso de um dia para o outro. Tendência é mais útil do que uma única pesagem.'],['Calorias e déficit energético','Caloria é uma unidade de energia. Quando, ao longo do tempo, a energia consumida fica abaixo da energia utilizada pelo organismo, existe déficit energético. Isso não significa comer o mínimo possível: uma estratégia precisa caber na vida real.'],['Metabolismo sem mistério','Seu corpo utiliza energia em repouso e também com movimento, exercício e digestão. Calculadoras estimam esse gasto, mas não substituem avaliação individual.'],['IMC: referência, não sentença','IMC = peso ÷ altura². É uma ferramenta de triagem, mas não mede diretamente gordura, massa muscular ou condicionamento. No VIDA, ele é apenas uma informação educativa.'],['Água, sono e movimento','Hidratação, sono e movimento não são atalhos mágicos, mas influenciam disposição, recuperação e capacidade de sustentar uma rotina.'],['Objetivos de comportamento','Além do resultado que deseja, escolha ações que dependem de você: registrar água, se movimentar, concluir conteúdos, organizar refeições e voltar rapidamente depois de um dia ruim.'],['Fechamento','Seu resultado é consequência de um processo. Um processo pode ser observado, aprendido e ajustado.']]},
2:{title:'Alimentação sem complicação',subtitle:'Aprenda a reconhecer o que existe no seu prato.',sections:[['Antes de falar de comida','Emagrecimento não precisa transformar comida em medo. O objetivo é reconhecer componentes das refeições e entender escolhas.'],['Macronutrientes','Proteínas, carboidratos e gorduras cumprem funções diferentes. Como referência educacional, proteína e carboidrato fornecem cerca de 4 kcal/g e gordura cerca de 9 kcal/g.'],['Proteína','Participa da manutenção de tecidos e pode contribuir para saciedade. Fontes incluem carnes, ovos, laticínios, soja, tofu e leguminosas.'],['Carboidrato','É uma importante fonte de energia e aparece em arroz, batata, mandioca, aveia, pães, massas, frutas e outros alimentos. Ter carboidrato não torna um alimento automaticamente ruim.'],['Gorduras','Fazem parte da alimentação e exercem funções importantes. Como são mais densas em energia, porções pequenas podem somar bastante energia sem que isso signifique eliminá-las.'],['Fibras e micronutrientes','Frutas, verduras, legumes, feijões, aveia, sementes e grãos integrais ajudam a aumentar variedade, fibras, vitaminas e minerais.'],['Como olhar uma refeição','Em um prato com arroz, feijão, frango, salada e azeite, você encontra carboidrato, proteína, fibras, micronutrientes e gordura. O objetivo é reconhecer, não rotular o prato como bom ou ruim.'],['Saciedade','Proteína, fibras, volume, hidratação, ritmo da refeição, sono e contexto podem influenciar satisfação depois de comer.'],['Fome x vontade','Pergunte quando foi a última refeição, se há sinais físicos de fome e qual contexto emocional existe. A ideia é consciência, não vigilância.'],['Comer fora e final de semana','Uma refeição diferente não precisa virar dia perdido. Retorne à rotina na próxima refeição, sem compensações extremas.'],['Fechamento','Você não precisa decorar calorias. O primeiro ganho é olhar para o prato e entender o que existe nele.']]},
3:{title:'Movimento que cabe na sua vida',subtitle:'Força, cardio, movimento diário e recuperação sem extremismo.',sections:[['Antes de falar de treino','O treino que mais cansa não é automaticamente o que mais funciona. A proposta é entender funções diferentes do movimento e do descanso.'],['Movimento começa antes do treino','Caminhar, subir escadas, deslocar-se e realizar tarefas também compõem seu movimento diário.'],['Treino de força','Musculação e outros exercícios resistidos estimulam força e musculatura. Preservar massa muscular é relevante durante perda de peso.'],['Cardio','Caminhada rápida, corrida, bicicleta, escada, dança e outras atividades podem melhorar condicionamento e contribuir para gasto energético.'],['Força ou cardio?','Eles não precisam competir. Uma rotina pode combinar força, cardio, movimento leve e descanso.'],['Caminhada e passos','Caminhada é ajustável e acessível. Passos podem ser usados como métrica de comportamento, não como número mágico universal.'],['Intensidade','Nem todo treino precisa ser máximo. O teste da fala ajuda a diferenciar esforço leve, moderado e intenso de forma educativa.'],['Progressão','Você pode evoluir em frequência, duração, carga, repetições, técnica ou ritmo. Não precisa aumentar tudo ao mesmo tempo.'],['Recuperação','Treino gera estímulo e recuperação permite adaptação. Dor forte, perda de função, tontura ou falta de ar incomum não devem ser ignoradas.'],['Uma semana possível','A melhor organização considera sua realidade. Um plano simples repetido costuma ser mais útil que um plano extremo abandonado.'],['Fechamento','Movimento não precisa ser punição pelo que você comeu. Pode ser parte de uma rotina de capacidade, condicionamento e autonomia.']]},
4:{title:'Não volte ao zero',subtitle:'Constância, retomada e os próximos passos depois do Dia 28.',sections:[['A parte mais importante começa agora','Depois da novidade inicial, aparecem compromissos, cansaço, refeições fora do planejado e dias imperfeitos. A habilidade central é aprender a voltar.'],['Motivação muda','Motivação oscila. Constância é criar estruturas simples o suficiente para acontecerem mesmo sem empolgação.'],['Constância não é perfeição','Perder um treino não apaga a semana. Fazer uma refeição diferente não apaga o processo. Constância é reduzir o tempo entre sair da rotina e voltar.'],['Não use punição','Jejum extremo, exercício excessivo e restrição agressiva podem alimentar ciclos de exagero e compensação. Retome seu padrão normal na próxima oportunidade.'],['Final de semana faz parte','Uma rotina sustentável precisa atravessar finais de semana, viagens e eventos sociais. Mantenha alguns pontos de referência e volte sem drama.'],['Balança e comparação','Peso continua sujeito a oscilações. Compare períodos, medidas, roupas, disposição, sono, movimento e capacidade de retomar. Compare principalmente Dia 1 x Dia 28.'],['Quando revisar a estratégia','Antes de reagir de forma extrema, revise execução, registros, sono, rotina e tendência. Ajuste é parte do processo.'],['Avaliação final','Repita as medidas nas condições mais parecidas possíveis e registre o que mudou, o que aprendeu e o que ainda exige atenção.'],['Próximos 30 dias','Escolha três comportamentos-base, uma frequência desejada e um plano B para cada um.'],['Gym Rats','O Projeto 28 ensinou a base. O Gym Rats entra como próxima fase de constância, usando o que você já aprendeu.'],['Fechamento','Você não volta ao zero. Você volta com experiência.']]}
};
const F=(title,description,fields=[],extras={})=>({title,description,kind:'form',fields,...extras});
const C=(title,items,description='Marque o que fizer sentido.')=>({title,description,kind:'form',checklist:items});
window.VIDA_MATERIALS={
1:[
F('Diagnóstico inicial','Registre seu ponto de partida sem julgamento.',[['name','Nome','text'],['date','Data','date'],['weight','Peso (kg)','number'],['height','Altura (cm)','number'],['waist','Cintura (cm)','number'],['abdomen','Abdômen (cm)','number'],['hip','Quadril (cm)','number'],['arm','Braço (cm)','number'],['thigh','Coxa (cm)','number'],['sleep','Média de sono (h)','number'],['water','Água aproximada (ml)','number'],['training','Treinos por semana','text'],['movement','Movimento diário','select','baixo|moderado|alto'],['goal','Principal objetivo','textarea'],['difficulty','Principal dificuldade','textarea'],['day28','O que gostaria diferente em 28 dias?','textarea']]),
{title:'Ficha de peso e medidas',description:'Compare seus registros sem transformar medição em obrigação.',kind:'measurements'},
F('Por que quero mudar?','Responda sem tentar agradar ninguém.',[['q1','O que me fez começar agora?','textarea'],['q2','O que gostaria de mudar no corpo, saúde ou rotina?','textarea'],['q3','O que já tentei antes?','textarea'],['q4','O que normalmente me faz desistir?','textarea'],['q5','Qual hábito mais me atrapalha?','textarea'],['q6','Qual hábito poderia facilitar?','textarea'],['q7','Sem a balança, como saberia que estou evoluindo?','textarea'],['q8','Como quero me sentir no Dia 28?','textarea']]),
F('Objetivo de resultado x comportamento','Separe desejo de ações sob seu controle.',[['result','Resultado que gostaria de alcançar','textarea'],['b1','Comportamento 1','text'],['b2','Comportamento 2','text'],['b3','Comportamento 3','text']],{note:'Se eu falhar um dia, volto no próximo registro — não na próxima segunda-feira.'}),
C('O que acompanhar além da balança',['cintura','abdômen','roupas','foto opcional','disposição','sono','frequência de treino','movimento','organização alimentar','capacidade de voltar','desempenho físico']),
C('Checklist da Semana 1',['Fiz meu diagnóstico inicial.','Registrei peso e medidas.','Entendi peso x gordura.','Entendi calorias e déficit.','Entendi meu IMC sem tratá-lo como diagnóstico.','Observei hidratação e sono.','Registrei treino ou movimento.','Defini objetivos de comportamento.','Fiz pelo menos 5 check-ins.']),
F('Meu acordo de 28 dias','Crie um compromisso realista.',[['priority','Eu vou priorizar','textarea'],['return','Quando sair da rotina, minha primeira ação será','textarea'],['support','Pessoa com quem posso compartilhar meu compromisso','text'],['reason','Por que vale continuar mesmo sem motivação?','textarea']]),
C('Peso subiu, e agora?',['Estou me pesando em condição parecida?','Comi mais sal ou carboidrato recentemente?','Treinei forte?','Meu ciclo pode alterar retenção?','Meu intestino está diferente?','Estou olhando um dia ou uma tendência?'],'Antes de concluir que engordou, revise o contexto.')
],
2:[
F('Guia rápido de proteínas','Exemplos: ovos, carnes, frango, peixes, laticínios, soja, tofu e leguminosas.',[['answer','Qual fonte aparece mais nas minhas refeições?','textarea']]),
F('Guia rápido de carboidratos','Exemplos: arroz, batata, mandioca, aveia, pão, massa, frutas, milho e tapioca.',[],{note:'Reconhecer não significa eliminar.'}),
F('Guia rápido de gorduras','Exemplos: azeite, castanhas, sementes, abacate e gorduras naturalmente presentes nos alimentos.',[],{note:'Gordura fornece aproximadamente 9 kcal/g.'}),
F('Guia de fibras','Fontes comuns: feijões, frutas, verduras, legumes, aveia, sementes e grãos integrais.',[['already','Quais já consumo?','textarea'],['more','Qual poderia aparecer mais vezes?','textarea']]),
C('Lista de compras inteligente',['ovos','frango/carne/peixe','iogurte/leite/queijo','feijão/lentilha/grão-de-bico','arroz','batata/mandioca','aveia','pão','frutas','folhas','legumes','azeite','castanhas/sementes','abacate'],'Monte uma lista com alimentos que você realmente consome.'),
F('Monte sua refeição','Ferramenta visual, não prescrição fixa.',[['protein','Fonte de proteína','text'],['carb','Fonte de carboidrato','text'],['produce','Vegetais/frutas','text'],['fat','Fonte de gordura','text'],['satiety','Essa combinação tende a me satisfazer?','select','sim|não|não sei']]),
{title:'Simulador educacional de macros',description:'Veja como macros viram energia. Não define quanto você deve consumir.',kind:'macro'},
{title:'Diário de fome e saciedade',description:'Observe fome antes e saciedade depois das refeições.',kind:'diary'},
F('Guia de bebidas e chás','Água, café e chás podem entrar na rotina. Nenhuma bebida derrete gordura.',[['reflection','Estou usando essa bebida porque gosto ou esperando efeito milagroso?','textarea']]),
F('Comer fora sem transformar em fracasso','Volte à rotina na próxima refeição, sem compensação extrema.',[['before','Como cheguei à refeição?','textarea'],['during','O que realmente quis comer e o que me satisfez?','textarea'],['after','O que aprendi para a próxima vez?','textarea']]),
C('Checklist da Semana 2',['Entendi macros.','Identifiquei proteína, carboidrato e gordura.','Observei fibras.','Montei uma refeição conscientemente.','Observei fome e saciedade.','Mantive hidratação registrada.','Revisei uma compra de alimentos.','Passei por uma refeição diferente sem transformar o dia em fracasso.','Completei os conteúdos.'])
],
3:[
{title:'Planner semanal de movimento',description:'Planeje o principal e um plano B para cada dia.',kind:'weektable'},
F('Tracker de treino','Registre a sessão e sua percepção.',[['date','Data','date'],['type','Tipo de treino','text'],['duration','Duração (min)','number'],['intensity','Intensidade','select','leve|moderada|intensa'],['before','Como me senti antes','textarea'],['after','Como me senti depois','textarea'],['adapt','Precisei adaptar algo?','textarea']]),
F('Tracker de movimento','Observe o movimento fora do treino.',[['minutes','Minutos ativos','number'],['steps','Passos, se acompanhar','number'],['sitting','Tempo sentado percebido','select','baixo|médio|alto'],['opportunity','Uma oportunidade de me movimentar mais amanhã','textarea']]),
F('Musculação x cardio','Força, cardio, movimento cotidiano e descanso têm funções diferentes e podem coexistir.',[]),
F('Escala simples de esforço','1–2 muito leve; 3–4 leve; 5–6 moderado; 7–8 intenso; 9 muito intenso; 10 máximo.',[['activity','Atividade','text'],['effort','Nota de esforço (1–10)','number'],['repeat','Eu conseguiria repetir amanhã?','select','sim|não|talvez']]),
F('Plano B para dias corridos','Defina a versão mínima antes do imprevisto.',[['nogym','Se não conseguir ir à academia','textarea'],['twenty','Se tiver só 20 minutos','textarea'],['tired','Se estiver cansada','textarea'],['rest','Se precisar descansar, vou evitar pensar que','textarea']]),
F('Exemplo de semana de movimento','Exemplo educacional: alterne força, caminhada/cardio, movimento leve e descanso.',[['adapt','Dias que realmente funcionam para mim','textarea']]),
C('Checklist de recuperação',['Estou dormindo razoavelmente?','Dor muscular está dentro do esperado?','Tenho dor forte/articular ou perda de função?','Minha disposição caiu muito?','Estou acumulando treino sem descanso?','Minha técnica piora por fadiga?']),
{title:'Biblioteca de exercícios',description:'Consulte nomes e demonstrações. A demonstração não determina se o exercício é adequado para você.',kind:'external',url:'https://musclewiki.com'},
F('Minha semana possível','Defina uma versão realista.',[['training','Quantidade realista de treinos','text'],['movement','Caminhadas/movimentos extras','text'],['hard','Dia mais difícil','text'],['planb','Plano B','textarea'],['signal','Sinal de que preciso reduzir intensidade','textarea']]),
C('Checklist da Semana 3',['Entendi movimento x treino.','Entendi força x cardio.','Registrei atividades.','Observei movimento fora do treino.','Criei um plano B.','Dei atenção à recuperação.','Não tratei intensidade máxima como obrigação.','Completei os conteúdos.'])
],
4:[
F('Avaliação final','Repita os dados em condições parecidas com o início.',[['date','Data','date'],['weight','Peso (kg)','number'],['waist','Cintura (cm)','number'],['abdomen','Abdômen (cm)','number'],['hip','Quadril (cm)','number'],['arm','Braço (cm)','number'],['thigh','Coxa (cm)','number'],['sleep','Média de sono','text'],['water','Água aproximada','text'],['training','Treinos/movimentos por semana','text'],['feeling','Como me sinto em comparação ao Dia 1?','textarea']],{final:true}),
{title:'Dia 1 x Dia 28',description:'Compare seu ponto de partida com o fechamento.',kind:'comparison'},
F('Minhas maiores vitórias','Registre mudanças que podem ou não aparecer na balança.',[['learned','Algo que aprendi','textarea'],['better','Algo que hoje faço melhor','textarea'],['surprise','Algo que me surpreendeu','textarea'],['hard','Algo difícil que mesmo assim continuei','textarea'],['offscale','Uma mudança que não aparece na balança','textarea']]),
C('O que ainda preciso melhorar',['hidratação','organização das refeições','proteína/fibras','treino','movimento diário','sono','planejamento de final de semana','voltar mais rápido depois de deslizes','outro'],'Escolha no máximo três prioridades.'),
F('Plano dos próximos 30 dias','Escolha três comportamentos para continuar.',[['h1','Hábito 1','text'],['h1f','Frequência','text'],['h1m','Versão mínima','text'],['h1b','Plano B','textarea'],['h2','Hábito 2','text'],['h2f','Frequência','text'],['h2m','Versão mínima','text'],['h2b','Plano B','textarea'],['h3','Hábito 3','text'],['h3f','Frequência','text'],['h3m','Versão mínima','text'],['h3b','Plano B','textarea']]),
F('Plano de retomada','Uma falha não precisa virar abandono.',[['first','Minha primeira ação simples será','textarea'],['second','Minha segunda ação será','textarea'],['old','A regra do passado que não quero repetir','textarea']]),
F('Revisão semanal pós-Projeto 28','Continue ajustando sem recomeçar do zero.',[['worked','O que funcionou?','textarea'],['blocked','O que atrapalhou?','textarea'],['adjust','O que vou ajustar?','textarea'],['win','Minha pequena vitória','textarea'],['priority','Prioridade da próxima semana','textarea']]),
F('Saiu da rotina?','Não use jejum punitivo, exercício para pagar comida ou restrição extrema. Volte à próxima refeição normal, hidrate-se e retome o planejamento.',[]),
C('Checklist final',['Fiz avaliação final.','Comparei Dia 1 x Dia 28.','Revisei peso e medidas sem tratar um número como sentença.','Identifiquei vitórias além da balança.','Escolhi três hábitos para continuar.','Criei meu plano de retomada.','Entendi como o Gym Rats entra na próxima fase.']),
F('Carta para mim mesma','Escreva poucas linhas para ler quando pensar em abandonar.',[['why','Eu comecei porque','textarea'],['learned','Em 28 dias eu aprendi que','textarea'],['remember','Quando estiver desanimada, quero lembrar que','textarea'],['action','Minha próxima ação possível sempre pode ser','textarea']]),
{title:'Ponte para o Gym Rats',description:'Você aprendeu. Agora é hora de sustentar. O Gym Rats será um ciclo de 45 dias focado em continuar aparecendo e transformar constância em jogo.',kind:'gym'}
]};
